### ISSUE TITLE
Google reCAPTCHA issue

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/CKs-FilterList#1]
I'm working on it. It might be broken for several pages since I stripped away the tracking token (which is required to see the pictures).

**Comment by The-Commissioner** [comment]
For google reCAPTCHA to work properly, script and frame(subdocument) should be allowed from `www.google.com` and script from `www.gstatic.com` should also be allowed.

Please try:
`@@||www.google.com^$script,subdocument`
`@@||www.gstatic.com^$script`

If this doesn't help some other program or addon is interferring.

**Comment by CHEF-KOCH** [comment]
I found out that the re-CAPTCHA data itself are coming from `gvt1.com` and it's sub-domain `redirector.gvt1.com`. 

I'll address this in the next commit. 

I guess I also need to do some cleanup, my test laptop shows that gstatic is global allowed in order to avoid such problems but it's not in the list, my fault. 😁

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/d623d635a282b4d6c2a8726e272fc047d57fc727

**Comment by CHEF-KOCH** [comment]
I make a new category for each pages which often gets updates aka Google, Reddit & Co. to avoid mistakes and to avoid overlooking something. Should be done in the next commit.
