### ISSUE TITLE
Adding CKs-FilterList to bigger projects

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/CKs-FilterList#16]
* ~~Request on [FilterLists](https://github.com/collinbarrett/FilterLists/) - [is out](https://github.com/collinbarrett/FilterLists/issues/297)!~~ [done]
* ~~Request on uBO -~~ I guess not from me because I and gorhill aren't really _friends_
* ~~Request on AdBlock -~~ [rejected without any explanation]
* ~~Request on AdGuard - not send yet [request is out]~~ Rejected without explanation 
* Request on other lists/repos - not send yet

I only send requests now to projects which are fully FOSS and non-profit since AdGuard & Co. basically getting money with their programs and integrated filter lists (which I don't like nor support).

**Comment by The-Commissioner** [comment]
> Request on AdGuard (not send yet) - Maybe @The-Commissioner can submit it?

You can rule me out talking to AdGuard ever again. The relationship is now too sour to fix. Infact, if anyone would ask me now, I would not recommend any of AdGuard's product to even my foes.

**Comment by The-Commissioner** [comment]
Also if I were you, I would wait for a little while, let the word spread out(possibly mention it out on your blog) and fix issues first. You would also not want to put the load on github by hosting it here(possible server requirement as well).

**Comment by CHEF-KOCH** [comment]
Okay thanks for clarification, I removed your comment about AdGuard due privacy reasons. 

As always thanks for your input.

**Comment by CHEF-KOCH** [comment]
I close here since I'm happy with the current situation. Filterlists is not a bad project.
