### ISSUE TITLE
Crackwatch.com ads are displayed

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/CKs-FilterList#2]
I'm working on it, the shown ads rotate so I have to find all ##[4353] etc ads in order to block it.

**Comment by The-Commissioner** [comment]
Please try:
`crackwatch.com##div[style="margin-top: 35px; text-align: center;"]`

**Comment by CHEF-KOCH** [comment]
Won't work.

I found the solution for almost all ads except the ##overlay.box(the big one you see visiting the front page). Strange part is that ##Overlay and ##.overlay-box is already in the list dunno why this isn't working. 

beb.crackwatch.com blocks all ads on the page itself.

**Comment by The-Commissioner** [comment]
That's strange it worked for me in both uBlock and AdGuard(extension as well as program).
Can you post screenshot of ad - so that I can see if we're on the same page or not?

**Comment by CHEF-KOCH** [comment]
It doesn't matter much now, crackwatch now added (yet again) other CND's and other BS. I need to re-do everything.

**Comment by CHEF-KOCH** [comment]
Solved with next update.
