### ISSUE TITLE
www.wetter.com not loading correctly

### ISSUE THREAD

**Issue by dabugen** [CHEF-KOCH/CKs-FilterList#20]
**Describe the site issue**
wetter.com does not load correctly, weather infos are missing if using your list.

### Test link:
www.wetter.com

### Reproduction steps:
Enable your list with uBlock Origin and go to www.wetter.com

### Environment specifications:
Chrome x64 with uBlock Origin, Windows 10.

- Filter list version: latest version from your site.
- Operating System and Version: Win 10
- Browser and Version: Chrome 64
- Adblocker and Version: uBlock Origin

**Comment by dabugen** [comment]
Sure :-) Thank you / Danke!

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/ae97769f093930fb5d0fdd4c33c43b630a7ea1c8
