### ISSUE TITLE
donation via paypal is not working

### ISSUE THREAD

**Issue by AddaxSoft** [CHEF-KOCH/CKs-FilterList#23]
I tried to support this project by donating, but I Get this:

![image](https://user-images.githubusercontent.com/6898938/41671405-4d8313f6-74b7-11e8-8ec3-7c381d1e0631.png)

**Comment by CHEF-KOCH** [comment]
I changed the donation to [liberapay](https://liberapay.com/CHEF-KOCH). PayPal gets finally unlocked next week.
