### ISSUE TITLE
Spotify IP Ranges blocking google.com

### ISSUE THREAD

**Issue by MainFighter** [CHEF-KOCH/CKs-FilterList#29]
Google is using one of the IP in the [Spotify Ad-Free ipranges.txt](https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/Corporations/Spotify%20Ad-Free/ipranges.txt). 

The range 216.58.192.0-216.58.223.255 blocks Google, google.com is currently using 216.58.199.78 for me in Australia.

nslookup: https://i.imgur.com/d2mOLpf.png

### Reproduction steps
Block the IP ranges (216.58.192.0-216.58.223.255) in [Spotify Ad-Free ipranges.txt](https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/Corporations/Spotify%20Ad-Free/ipranges.txt)

### Environment specifications
- Filter list version: v1.13
- Operating system and version: Windows 10 Enterprise 17134.165
- Browser and version: Chrome 67.0.3396.99
- Adblocker and version: Windows Firewall

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/860074ef3423e328049a7caacf25177ccad2bc88
