### ISSUE TITLE
Spotify Ad-Filter Blocks audio streaming {Spotify Desktop}

### ISSUE THREAD

**Issue by ZeroDot1** [CHEF-KOCH/CKs-FilterList#31]
If you use the list, no audio is started.
The following URLs need to be removed to solve the problem:
```bash
audio-fac.spotify.com
heads-fa.spotify.com
```

### Reproduction steps
Import the list into the AdBlocker and then start Spotify. 

### Environment specifications

- Filter list version: 0.0.1.7
- Operating system and version: Linux/BSD
- Browser and version: Spotify Dektop
- Adblocker and version: pfBlockerNG/pfSense/Pi-hole

**Comment by CHEF-KOCH** [comment]
heads-fa.spotify.com is for ads and audio-fac.spotify.com points directly to beta.spotify.map.fastly.net.

Which Spotify server you use? Washington? Cause this is:
* audio-sp-dca.spotify.com
* audio-sp-dca6.spotify.com
* audio-sp-fra.spotify.com

.. and should not even call the mentioned domains except for ads.
