### ISSUE TITLE
OCSP-Server Blocked in [CK's Game HOSTS Filter List] like letsencrypt, comodo, verisign

### ISSUE THREAD

**Issue by HeCPX** [CHEF-KOCH/CKs-FilterList#32]
I am using the "CHEF-KOCH's Game HOSTS Filter List"
`https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Game-HOSTS-FilterList.txt`
and there are several OCSP-Servers for Certificate-Validation (e.g. if its revoked or not) that are blocked.

Like:
- ocsp.verisign.com
- ocsp.comodoca.com
- ocsp.int-x3.letsencrypt.org
- ocsp.godaddy.com

Is there a reason for this?

I think it's actually more unsecure to block these domains, because you dont know about a revoked (stolen, lost, etc.) certificate.

Would be happy, if someone could explane me this :)

### Environment specifications

- Filter List: CHEF-KOCH's Game HOSTS Filter List
- Filter list version: TimeUpdated: 2018-07-07	10:58:25+01:00 # Version: 0.0.0.1
- Operating system and version: Debian Stretch

**Comment by CHEF-KOCH** [comment]
The idea is to block all background communication but you definitely have a point. Especially in case, you play online games (for example MMO based or shooters which def. need an active internet connection). 

I'll remove this an make a separate list which is designed to block all traffic coming from the OS itself. SO everyone can decide to use it or not.

**Comment by HeCPX** [comment]
Hey,

thanks for the answer. I just use nearly all of your lists, just in case :) (Not gaming at all.)
But its quite nice to know and hear that you will seperate this into another new list where alle the OS traffic will be bundled.
Similar to this: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt and maybe not only specific for windows?

After some time i could also follow your thoughts:
Maybe if the server doesnt support OCSP Stapling then the CAs could sniff your browsing history by the OCSP checks. Well, normally there are so many CAs that one even gets a check every few minutes. So one doesnt know all.
But im not this deep into that topic to evaluate this... Maybe its just a wrong thougt of me

**Comment by CHEF-KOCH** [comment]
OCSP-Servers + MS related connections getting their own list.
