### ISSUE TITLE
A few entries to add for Adobe

### ISSUE THREAD

**Issue by kronflux** [CHEF-KOCH/CKs-FilterList#37]
Over the years I've been collecting Adobe domains and IP's, and you've done essentially the same exact work I had, with more entries than mine.

That being said, I have a few that you don't have, which belong to adobe and are used for various services.
In case you feel like adding them, here they are! :)

`0.0.0.0 192.150.14.69`
`0.0.0.0 192.150.18.101`
`0.0.0.0 192.150.18.108`
`0.0.0.0 192.150.22.40`
`0.0.0.0 192.150.8.100`
`0.0.0.0 192.150.8.118`
`0.0.0.0 ccmdl.adobe.com`
`0.0.0.0 ccmdls.adobe.com`
`0.0.0.0 ims-prod06.adobelogin.com`
`0.0.0.0 swupdl.adobe.com`
`0.0.0.0 swupmf.adobe.com`
`0.0.0.0 www.du1.adobe.com`

PS: Awesome work on these lists btw! I'm really impressed by how thorough they are ❤️

**Comment by CHEF-KOCH** [comment]
I'll add them except the IP's (cause I'm not a fan of IP blocking) instead I'll add the proper reverse + ns records.

reverse dns

`activate-sjc0.adobe.com`


ns record

```bash
adobe-dns-01.adobe.com
a1-217.akam.net
a7-64.akam.net
a10-64.akam.net
a28-67.akam.net
a26-66.akam.net
adobe-dns-02.adobe.com
a13-65.akam.net
... <around 500 more>
```

Thanks for submitting.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/d9cd7170d30bfbfa13625297ce4fd9238e9367e8
