### ISSUE TITLE
Spotify Ad-Free lists blocks almost all images

### ISSUE THREAD

**Issue by OberstFredward** [CHEF-KOCH/CKs-FilterList#43]
Your list also blocks all pictures of the artists / albums / songs. Only the pictures of the "Browse"-section are loaded.

I don't get any ads. Great list!
(I'm using the Spotify client on linux/ubuntu)

**Comment by CHEF-KOCH** [comment]
[Filter-Policy-&-Issue-Tickets](https://github.com/CHEF-KOCH/CKs-FilterList/wiki/Filter-Policy-&-Issue-Tickets).
