### ISSUE TITLE
8ch and 7 chan why were they blocked at all?

### ISSUE THREAD

**Issue by bogachenko** [CHEF-KOCH/CKs-FilterList#48]
||8ch.net^
||7chan.org^
Blocking 2 of these sites is not needed. it interferes with visiting on them. there is nothing to fear. simple boards as 4chan

**Comment by CHEF-KOCH** [comment]
[No](https://en.wikipedia.org/wiki/8chan).

**Comment by bogachenko** [comment]
And what exactly should I have read on wikipedia? Could you quote?

**Comment by CHEF-KOCH** [comment]
".. The Daily Dot wrote that boards do exist to share sexualized images of minors in provocative poses, and that some users of those boards do post links to explicit child pornography hosted elsewhere."!

**Comment by bogachenko** [comment]
How does child pornography relate to my security (or advertising, of course, not advertising of child pornography)?

Is this list serves to combat pedophiles. I do not think so. same (quote ads-tracker.txt)
> A comprehensive, all-in-one ad-block list for blocking of trackers, pop-up ads, ads, unwanted cookies, fake news, cookie warning messages, unwanted comment sections, crypto-coin mining, YouTube clutter and social network hassles.

Do you want to bring pedophilia under it?

> unwanted comment sections

ehhhhhh
