### ISSUE TITLE
Google My Business - Cookie & GDPR Warning Removal

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#53]
**Describe the site issue**
It seems that **CHEF-KOCH's Cookie & GDPR Warning Removal Filter List** is blocking **Google My Business**, by making it white blank.

### Test link
https://www.google.com/business/

### Screenshot of the web page (_optional_)
- Blank White page

### Screenshot of the developer console (**if possible**)
![console](https://user-images.githubusercontent.com/16375271/50488252-43812a80-0a0a-11e9-9b8f-64f6ad565287.png)

### Reproduction steps
1. Activate the "CHEF-KOCH's Cookie & GDPR Warning Removal Filter List"
2. Go to https://www.google.com/business/
3. "Profit"

### Environment specifications

- Filter list version:  0.0.0.21
- Operating system and version: Windows 10 Pro - Version 1803 - Build 17134.137
- Browser and version: Chrome 72.0.3626.28 (Official Build) beta (64-bit)
- Adblocker and version: uBlock Origin 1.17.4

### Add any other additional helpful information (_optional_)
![filter](https://user-images.githubusercontent.com/16375271/50488519-99a29d80-0a0b-11e9-8733-b263d77f8d89.png)

**Comment by ArmynC** [comment]
Something is not right. I installed again (https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/cookies.txt) and it's the same. I wouldn't do this if I wasn't so sure...

PS: Check my website (https://arminc.tk/) for my uBlock0 pre-made Settings and try to restore them if you want.

**Comment by CHEF-KOCH** [comment]
```bash
"selectedFilterLists": [
    "https://github.com/kowith337/ThaiAntiTokenSites/raw/master/AntiPumpSites.txt",
    "https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt",
    "https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/filterlist/other/MiscAnnoynace.txt",
    "https://raw.githubusercontent.com/lightswitch05/hosts/master/tracking-aggressive-extended.txt",
    "https://www.i-dont-care-about-cookies.eu/abp/",
    "https://github.com/bigdargon/hostsVN/raw/master/hosts",
    "https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt",
    "https://cdn.adblockcdn.com/filters/easylist_lite.txt",
    "https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Spotify/Spotify-AdBlock.txt",
    "https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Popads.txt",
    "https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt",
    "https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/malware.txt",
    "https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/coinminer.txt",
    "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/I%20Don't%20Want%20to%20Download%20Your%20Browser.txt",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-'Notification%20pre-prompt%20banners'%20List.txt",
    "http://malwaredomains.lehigh.edu/files/immortal_domains.txt",
    "http://malwaredomains.lehigh.edu/files/justdomains",
    "http://sysctl.org/cameleon/hosts",
    "http://www.urlvir.com/export-hosts/",
    "https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt",
    "https://hosts.nfz.moe/full/hosts",
    "https://raw.githubusercontent.com/AegisTeam/Discord-Resources/master/Domain%20Filters/Malicious/Screamers",
    "https://raw.githubusercontent.com/AegisTeam/Discord-Resources/master/Domain%20Filters/master",
    "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts",
    "https://raw.githubusercontent.com/Lerist/Go-Hosts/master/hosts-ad",
    "https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt",
    "https://raw.githubusercontent.com/anarki999/Adblock-List-Archive/master/Better.fyiTrackersBlocklist.txt",
    "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt",
    "https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt",
    "https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
    "https://someonewhocares.org/hosts/zero/hosts",
    "https://stopforumspam.com/downloads/toxic_domains_whole.txt",
    "https://v.firebog.net/hosts/Prigent-Ads.txt",
```

You use too many filter lists, some of them are outdated or not maintained or merged in other lists. Using e.g. Windows Spy Blocker list in a browser doesn't make any sense.

**Comment by ArmynC** [comment]
But what is the problem? Like the other filters are working well... I'll try anyway to see where is the conflict. Thanks anyway.

**Comment by CHEF-KOCH** [comment]
I'm not wasting my time debugging other filter lists. Sorry, remove all of them, purge the cache and only use mine, if something is missing make a pull request and I keep an eye on them. 

More is not better in uBlock or uMatrix, most of the mentioned lists are heavily outdated. E.g. `Prebake - Filter Obtrusive Cookie Notices` was `28 May 2018 14:00 UTC`. Most of these rules are redundant anyway. One of the list blocks some legitimate Google things.

**Comment by ArmynC** [comment]
Oh about prebake I forgot to remove it.. I added it today by accident, I knew about the merged state... I'll try now to see what's goin' and report...

**Comment by ArmynC** [comment]
Hmm... Maybe the Prebake filter was the problem, I tried again after removing it and some others (1,2,3) and it works at this moment. Thanks :)

**Comment by CHEF-KOCH** [comment]
* http://www.urlvir.com/export-hosts/
* https://hosts.nfz.moe/full/hosts

These list are also for uMatrix or for HOSTS directly and causing uBo to load even longer and consume more memory than necessary. 

It also doesn't make sense to add 1 million domains (which you never visit) or your Browser never connect, as stated in the Readme, there is no security benefit. If you want to configure uBO in "lockdown-mode" I suggest you use [hard-mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) instead + disable JavaScript which faces already 95% of all security implications.
