### ISSUE TITLE
[Reddit Filter List] Missing search bar and navigation filter

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#54]
**Describe the site issue**
The Reddit top bar (header) and posts placement is wrong.

### Test link
https://www.reddit.com/r/uBlockOrigin/

### Screenshot of the web page (_optional_)
![header](https://user-images.githubusercontent.com/16375271/50512919-79bbba00-0a9d-11e9-86dc-9f77e1f06df2.png)
![post](https://user-images.githubusercontent.com/16375271/50513868-25b3d400-0aa3-11e9-95b2-2446e5d7b01e.png)

### Screenshot of the developer console (**if possible**)
![console](https://user-images.githubusercontent.com/16375271/50513018-e33bc880-0a9d-11e9-9500-22cd377e8672.png)

### Reproduction steps
1. Go to https://www.reddit.com/r/uBlockOrigin/
2. Check the bar

### Environment specifications

Filter list version: 0.0.0.76
Operating system and version: Windows 10 Pro - Version 1803 - Build 17134.137
Browser and version: Chrome 72.0.3626.28 (Official Build) beta (64-bit)
Adblocker and version: uBlock Origin 1.17.4

### Add any other additional helpful information (_optional_)
[My day-to-day settings, all filters active (with this filter disabled at this time)](https://arminc.tk/uBlock0%20%E2%96%B6%20Settings%20(with%20Filters)/ArminC_uBlock0_Settings.txt)
[Just the Reddit Filter active - Settings](https://arminc.tk/uBlock0%20%E2%96%B6%20Settings%20(with%20Filters)/test_do_not_use.txt)

* All filters are disabled, except this one and the bug is still there.
* I did purged all the caches.

**Comment by CHEF-KOCH** [comment]
Should be fixed now 🤔 ?!

**Comment by ArmynC** [comment]
Purged + Updated.. and I don't think so...

![capture2](https://user-images.githubusercontent.com/16375271/50567531-da255280-0d4e-11e9-98e1-db46df3f1029.PNG)
![capture](https://user-images.githubusercontent.com/16375271/50567532-da255280-0d4e-11e9-9be6-fb4d93eba487.PNG)

**Comment by CHEF-KOCH** [comment]
Will be fixed in the next bigger release.

**Comment by ArmynC** [comment]
Oh so you couldn't manage to fix it, right?

**Comment by CHEF-KOCH** [comment]
I re-write some rules cause I'm not happy with the current ones.

**Comment by ArmynC** [comment]
Ok. Until then I will disable it.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/affc37aaa853bc1f612f9bc9ac13f01762ad0be4
