### ISSUE TITLE
[Facebook Filter] Facebook Button

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#55]
**Describe the site issue**
The menu button is placed wrong on the left side (instead of the right if OFF).

### Test link
https://www.facebook.com/dan.andronic.9

### Screenshot of the web page (_optional_)
![capture](https://user-images.githubusercontent.com/16375271/50517021-c9f34600-0ab6-11e9-9fde-ec724ea305ab.PNG)

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
-

### Environment specifications

Filter list version: 0.0.3.58
Operating system and version: Windows 10 Pro - Version 1803 - Build 17134.137
Browser and version: Chrome 72.0.3626.28 (Official Build) beta (64-bit)
Adblocker and version: uBlock Origin 1.17.4

### Add any other additional helpful information (_optional_)
-

**Comment by ArmynC** [comment]
-- After the person created another post, the buttons are now correctly arranged.

When I created this issue topic, only 1 of that posts had this problem, more precisely the newest one (see the photo). I don't know what caused this thing to be fixed. The settings are the same, I turned off all the other filters and kept this one active to ensure that this one is the cause, and so it was. I'll try to see if it's coming again ❕❔

**Comment by CHEF-KOCH** [comment]
It's normal, such pages like reddit and facebook almost daily change something on their pages, sometimes you even see some "experiments". 

I'm not going to change it anytime soon since Facebook is my lowest priority.

**Comment by ArmynC** [comment]
Yeah, I thought about that... if it isn't a priority isn't a better solution to remove all the rules that mess with the facebook site structure?

**Comment by CHEF-KOCH** [comment]
It gets separated, anti-corp for blocking facebook and I guess the top 500 domains getting their own lists because they need to adjust almost weekly (no man-power currently in order to archive the goal).

**Comment by ArmynC** [comment]
Little update 😮 Now with the Facebook filter.. the 'Photos' of a page aren't showing until you press 'See all' (anyway I won't use it because Fb is unstable) but I wanted you to know..
