### ISSUE TITLE
friendlyarm.com

### ISSUE THREAD

**Issue by EvilOlaf** [CHEF-KOCH/CKs-FilterList#56]
Hello,

not sure if this is a mistake or not but I noticed that `friendlyarm.com` as well as `www.friendlyarm.com` have been added to "CHEF-KOCH's HOSTS Ad- & Tracker Filter List" and are still present in version 0.0.2.76.

Friendlyarm are creators and distributors of SBCs like NanoPC and NanoPi.

Could you please review this decision? 

I am using Pi-Hole v4.1.1 if this is relevant.

Thanks for reading.

**Comment by CHEF-KOCH** [comment]
The often got hacked or compromised and that's why they went onto the list but I removed them now.
