### ISSUE TITLE
Ads & Tracker list removes some social functions - is this intended? 

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#58]
**Describe the site issue**
It removes (like social annoyance filter) some social buttons (but not all). Is this intended? Thanks..

### Test link
https://www.stiripesurse.ro/ziarul-francez-le-monde-pune-romania-la-colt-cu-ocazia-preluarii-presedintiei-consiliului-ue-pe-calea-ungariei-i-a-poloniei_1314766.html

### Screenshot of the web page (_optional_)
![capture](https://user-images.githubusercontent.com/16375271/50563936-a7b52e80-0d29-11e9-871c-3ece14bb6188.PNG) (OFF)
![capture1](https://user-images.githubusercontent.com/16375271/50563937-a97ef200-0d29-11e9-957c-f58d4e199c15.PNG) (ON)

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
-

### Environment specifications

- Filter list version: Latest Ad & Track filter
- Operating system and version: -
- Browser and version: -
- Adblocker and version: -

### Add any other additional helpful information (_optional_)
-

**Comment by CHEF-KOCH** [comment]
The hidden buttons are indicators on how often it was liked/shared which does nothing on the page except exposing you to more trackers. It's on purpose.
