### ISSUE TITLE
Slimmed Filter breaks the Unsubscribe Button

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#61]
**Describe the site issue**
_I think_ that the extension is blocking the Unsubscribe Button

### Test link
youtube.com

### Screenshot of the web page (_optional_)
-

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
1. Subscribe on some channel
2. Try to press unsubscribe

### Environment specifications

- Filter list version: Latest
- Operating system and version: -
- Browser and version: -
- Adblocker and version: -

### Add any other additional helpful information (_optional_)
-

**Comment by CHEF-KOCH** [comment]
Missing information -> invalid.
