### ISSUE TITLE
G-Mail Hidden Buttons

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#64]
**Describe the site issue**
CHEF-KOCH's PopAds HOSTS Filter List blocks the G-Mail buttons.

### Test link
https://mail.google.com/mail/u/0/#inbox

### Screenshot of the web page (_optional_)
![capture](https://user-images.githubusercontent.com/16375271/50765379-a033df00-126d-11e9-9b32-cd70f518174e.PNG)

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
Log In and check the body...

### Environment specifications

- Filter list version: 0.0.1.02
Operating system and version: Windows 7 x64 SP1 (latest updates)
Browser and version: Chrome Beta 72
Adblocker and version: uBlock 1.17.4

### Add any other additional helpful information (_optional_)
||www.gstatic.com^
Ex. https://www.gstatic.com/images/icons/material/system/1x/arrow_back_black_20dp.png

**Comment by ArmynC** [comment]
![capture](https://user-images.githubusercontent.com/16375271/50766316-a081a980-1270-11e9-996f-3d873317e7be.PNG)

**Comment by CHEF-KOCH** [comment]
Oh that's correct then, was already out of the list but I forgot to comment, sorry then the ticket was valid.
