### ISSUE TITLE
DIV + Ins list removes Facebook chat function - is this intended?

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#65]
**Describe the site issue**
CHEF-KOCH's DIV + Ins Filter List remove the Facebook Chat. Is this intended?

### Test link
https://www.facebook.com/PartidAliantaNationala/

### Screenshot of the web page (_optional_)
![capture](https://user-images.githubusercontent.com/16375271/50791712-908eb780-12ba-11e9-97dd-198814ec1732.PNG)

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
1. Go to the link 
2. Enable the filter
3. The Comments disappear

### Environment specifications

Filter list version: 0.0.0.10
Operating system and version: Windows 7 x64 SP1 (latest updates)
Browser and version: Chrome Beta 72
Adblocker and version: uBlock 1.17.4

### Add any other additional helpful information (_optional_)

From what I have seen, these are blocked by the filter:

```
##div[class*="advert"]
##div[class*="Ad"]
```

**Comment by CHEF-KOCH** [comment]
* You use too many filter lists, it's mentioned that this causes only problems and doesn't offer more. 
* You can use the cosmetical blocking button to toggle it, which won't break anything else. 

![feeffe](https://user-images.githubusercontent.com/727123/51052589-69e0c180-15d7-11e9-99e8-938203d553aa.png)

If I unlock the div rules it only triggers additional problems especially on Facebook and there is no div whitelist function for uBO.
