### ISSUE TITLE
Problematic rule : ||www.youtube-nocookie.com^

### ISSUE THREAD

**Issue by StanGets** [CHEF-KOCH/CKs-FilterList#66]
Hi,

Ever since I've been using YouTube I've read pros and cons concerning youtube-nocookie.com

Pros ultimately lead to a dedicated Firefox extension : [Privacy Enhanced Mode for Embedded YouTube](https://addons.mozilla.org/en-US/firefox/addon/youtube-nocookie/)

Cons include this one filter, `||www.youtube-nocookie.com^`, found in _CHEF-KOCH's Ads & Tracker Filter List_

I'm no expert so I'd really wish to know who is right and who is wrong.

I run the uBlockO extension under Firefox and at this time I have to add the `@@||www.youtube-nocookie.com^` rule in _My filters_ in orer to view YouTube videos on sites using youtube-nocookie to access them. Am I right?

I'm really confused with this no-cookie YouTube feature. What am I missing?

Thanks!

**Comment by bogachenko** [comment]
@StanGets Don't look for logic in his actions. He once blocked imageboard, due to the fact that the people there have downloaded child porn

**Comment by StanGets** [comment]
@bogachenko if I use 3 CHEF-KOCH' filter lists it is because I happen to find them pertinent, and there may be exceptions in whatever lists or i may totally mistaking.

- CHEF-KOCH's Ads & Tracker Filter List
- CHEF-KOCH's Google Filter List
- CHEF-KOCH's Reddit Filter List

include filters I find for some nowhere else and lead to no issues up to now.

Whatever, the youtube-no-cookie remains problematic for me, with or without a given filter.

**Comment by bogachenko** [comment]
@StanGets 
> there may be exceptions in whatever lists

lol, he has them more than usual

I used this list CHEF-KOCH's Ads & Tracker Filter List. Read the name. And tell me does child porn belong to him? I tried to talk to him, just like you, making arguments. He deleted the comments and blocked the thread 

Ps I wish you good luck

**Comment by StanGets** [comment]
@bogachenko the simple fact of evoking child porn brings me close to puking but since you evoke the correlation between anti-ads/trackers and vice I'm of course obliged to agree on the fact there is none, unless to consider a-priori that sites devoted to vice are more likely to include trackers if not ads.

I take my chance with CHEF-KOCK, never had the opportunity to dialog with him. You seem to know him, at least sufficiently to have an opinion. I happen to be of those who believe or not on the basis of their own experiences :=) I'll wait and see if the boogeyman is naughty or not, lol!

**Comment by CHEF-KOCH** [comment]
I take every report serious and there is no point in starting a drama if you think my rules are breaking things then start an issue ticket (according to the rules which you accepted by joining the project or by doing a PR). 

To answer the question, the nocookie domain is a part of the GDPR which is triggered whenever you work with Youtube www or embeds. It's basically the "no tracking" opt-in solution for YouTube, however it's not necessary to trust it and I provide some rules already in order to not break some websites. 

The off-topic comments are removed now + it's an invalid issue ticket since this is a question. 

Other people would not have wasted their time, I was so kind to answer the question.

**Comment by StanGets** [comment]
> I take every report serious and there is no point in starting a drama if you think my rules are breaking things then start an issue ticket (according to the rules which you accepted by joining the project or by doing a PR).

No drama my friend unless to consider that a question is by nature dramatic.

> To answer the question, the nocookie domain is a part of the GDPR which is triggered whenever you work with Youtube www or embeds. It's basically the "no tracking" opt-in solution for YouTube, however it's not necessary to trust it and I provide some rules already in order to not break some websites.

That answers nothing. "_it's not necessary to trust it and I provide some rules already in order to not break some websites._" is factual and the very reason I exposed my question.

Thanks anyway. I'll search elsewhere for information regarding this youtube-nocookie feature as I have already, likely I'll be again confronted to pros and cons.

A pity you close what is obviously a non-issue given its a simple question regarding one of your filters.

Take care.

**Comment by CHEF-KOCH** [comment]
It still places a cookie, that's why it's blocked (I also added reference links).

**Comment by StanGets** [comment]
> It still places a cookie, that's why it's blocked (I also added reference links)

Got it, thanks.

> You also don't need the "Privacy Enhanced Mode for Embedded YouTube" extension while using my filter list.

I don't use that extension, I evoked it above only to point out that Youtube-nocookie was sufficiently considered by some developers to get them create a dedicated extension. It is this hiatus between pros (like this developer) and cons (as yourself and others) which got me to open this non-issue.

Whatever, I appreciate and use your lists, and that's the main point.
