### ISSUE TITLE
Game Filter List blocks Facebook

### ISSUE THREAD

**Issue by mastersonb** [CHEF-KOCH/CKs-FilterList#67]
Line 75 and 76 completely block Facebook functionality. Not sure if this is intended.

**Comment by CHEF-KOCH** [comment]
Jupp, it's intended in order to block social media news and login since you play I game I don't see any reason to unblock it.

If you tell me the name of the game and why it's important I would consider to remove it.

**Comment by mastersonb** [comment]
I would say some games use Facebook for login however in this case it seems like I've misunderstood how you intend the list to be used.

**Comment by CHEF-KOCH** [comment]
I might comment on Google, Facebook and Twitter out in the next commit but it's unclear if those login fields are not submitting some metadata or placing a cookie or not (even if you don't use them) since the GDPR thingy does not apply in other countries.
