### ISSUE TITLE
Please delete the CoinBlockerLists! IMMEDIATELY!

### ISSUE THREAD

**Issue by ZeroDot1** [CHEF-KOCH/CKs-FilterList#68]
Please delete the contents of the CoinBlockerLists from your lists. I do not accept that the CoinBlockerLists are offered in your repository.

To ALL CoinBlockerLists users please always visit the Official pages:  https://gitlab.com/ZeroDot1/CoinBlockerLists

**Comment by CHEF-KOCH** [comment]
I do not accept trolls.
