### ISSUE TITLE
blocking "googlehosted.l.googleusercontent.com" causes issues with Google Apps + User Content

### ISSUE THREAD

**Issue by CraftyBIT** [CHEF-KOCH/CKs-FilterList#74]
line 1176 of Spotify-HOSTS.txt (0.0.0.0 googlehosted.l.googleusercontent.com) causes Google Drive and especially Google Photos to not function properly (in the case of Photos, not at all), as well as other parts of the Google system (such as chrome extensions). The Google apps were fixed for me after I commented it out in my hosts file.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/46b20c68b30a5190a8fe8e9a8b8659558e501aa5
